<template>
    <div class="loadingio-spinner-spinner-5rybxsg2ye4"><div class="ldio-z3cv1aj5l2g">
    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div></div>
</template>
    <style lang="scss" scoped>
    @keyframes ldio-z3cv1aj5l2g {
      0% { opacity: 1 }
      100% { opacity: 0 }
    }
    .ldio-z3cv1aj5l2g div {
      left: 79.42999999999999px;
      top: 40.56px;
      position: absolute;
      animation: ldio-z3cv1aj5l2g linear 1s infinite;
      background: #220b09;
      width: 10.14px;
      height: 20.28px;
      border-radius: 5.07px / 10.14px;
      transform-origin: 5.07px 43.94px;
    }.ldio-z3cv1aj5l2g div:nth-child(1) {
      transform: rotate(0deg);
      animation-delay: -0.9166666666666666s;
      background: #220b09;
    }.ldio-z3cv1aj5l2g div:nth-child(2) {
      transform: rotate(30deg);
      animation-delay: -0.8333333333333334s;
      background: #d34c31;
    }.ldio-z3cv1aj5l2g div:nth-child(3) {
      transform: rotate(60deg);
      animation-delay: -0.75s;
      background: #e88432;
    }.ldio-z3cv1aj5l2g div:nth-child(4) {
      transform: rotate(90deg);
      animation-delay: -0.6666666666666666s;
      background: #ff312d;
    }.ldio-z3cv1aj5l2g div:nth-child(5) {
      transform: rotate(120deg);
      animation-delay: -0.5833333333333334s;
      background: #f5c037;
    }.ldio-z3cv1aj5l2g div:nth-child(6) {
      transform: rotate(150deg);
      animation-delay: -0.5s;
      background: #e89788;
    }.ldio-z3cv1aj5l2g div:nth-child(7) {
      transform: rotate(180deg);
      animation-delay: -0.4166666666666667s;
      background: #fd3262;
    }.ldio-z3cv1aj5l2g div:nth-child(8) {
      transform: rotate(210deg);
      animation-delay: -0.3333333333333333s;
      background: #f0c3a9;
    }.ldio-z3cv1aj5l2g div:nth-child(9) {
      transform: rotate(240deg);
      animation-delay: -0.25s;
      background: #9d9aca;
    }.ldio-z3cv1aj5l2g div:nth-child(10) {
      transform: rotate(270deg);
      animation-delay: -0.16666666666666666s;
      background: #645481;
    }.ldio-z3cv1aj5l2g div:nth-child(11) {
      transform: rotate(300deg);
      animation-delay: -0.08333333333333333s;
      background: #220b09;
    }.ldio-z3cv1aj5l2g div:nth-child(12) {
      transform: rotate(330deg);
      animation-delay: 0s;
      background: #d34c31;
    }
    .loadingio-spinner-spinner-5rybxsg2ye4 {
      width: 169px;
      height: 169px;
      display: inline-block;
      overflow: hidden;
      position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
      background: rgba(241, 242, 243, 0);
    }
    .ldio-z3cv1aj5l2g {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-z3cv1aj5l2g div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
    </style>