<template>
	<div class="loadingio-spinner-dual-ring-6572u18ty7y"><div class="ldio-1qaihz8z7hy">
<div></div><div><div></div></div>
</div></div>

</template>
<style scoped>
	@keyframes ldio-1qaihz8z7hy {
	  0% { transform: rotate(0) }
	  100% { transform: rotate(360deg) }
	}
	.ldio-1qaihz8z7hy div { box-sizing: border-box!important }
	.ldio-1qaihz8z7hy > div {
	  position: absolute;
	  width: 72px;
	  height: 72px;
	  top: 14px;
	  left: 14px;
	  border-radius: 50%;
	  border: 8px solid #000;
	  border-color: #ff0033 transparent #ff0033 transparent;
	  animation: ldio-1qaihz8z7hy 0.14771048744460857s linear infinite;
	}
	.ldio-1qaihz8z7hy > div:nth-child(2) { border-color: transparent }
	.ldio-1qaihz8z7hy > div:nth-child(2) div {
	  position: absolute;
	  width: 100%;
	  height: 100%;
	  transform: rotate(45deg);
	}
	.ldio-1qaihz8z7hy > div:nth-child(2) div:before, .ldio-1qaihz8z7hy > div:nth-child(2) div:after { 
	  content: "";
	  display: block;
	  position: absolute;
	  width: 8px;
	  height: 8px;
	  top: -8px;
	  left: 24px;
	  background: #ff0033;
	  border-radius: 50%;
	  box-shadow: 0 64px 0 0 #ff0033;
	}
	.ldio-1qaihz8z7hy > div:nth-child(2) div:after { 
	  left: -8px;
	  top: 24px;
	  box-shadow: 64px 0 0 0 #ff0033;
	}
	.loadingio-spinner-dual-ring-6572u18ty7y {
	  width: 39px;
	  height: 39px;
	  display: inline-block;
	  overflow: hidden;
	  background: none;
	}
	.ldio-1qaihz8z7hy {
	  width: 100%;
	  height: 100%;
	  position: relative;
	  transform: translateZ(0) scale(0.39);
	  backface-visibility: hidden;
	  transform-origin: 0 0; /* see note above */
	}
	.ldio-1qaihz8z7hy div { box-sizing: content-box; }
	/* generated by https://loading.io/ */
	</style>